spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=DEMO2;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# secret key for JWT
jwt.secret=E9HbPdEuH4hZ4ZAt1qsk3LIV8efLoAyM
spring.jpa.hibernate.ddl-auto=update
